export const RESET = 'RESET'
export const START_LOADING = 'START_LOADING'
export const CLOSE_LOADING = 'CLOSE_LOADING'
export const TOGGLE = 'TOGGLE'

export const ADD_PANE = 'ADD_PANE'
export const REMOVE_PANE = 'REMOVE_PANE'
export const SET_PANE_STATE = 'SET_PANE_STATE'
export const SET_PANE_ACTIVEKEY = 'SET_PANE_ACTIVEKEY'

export const GET_MENU = 'GET_MENU'
export const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS'

export const GET_ROLE_TREE = 'GET_ROLE_TREE'
export const GET_ROLE_TREE_COMPLETE = 'GET_ROLE_TREE_COMPLETE'

export const GET_THISROLE = 'GET_THISROLE'
export const GET_THISROLE_SUCCESS = 'GET_THISROLE_SUCCESS'

export const GET_TODOCOUNT = 'GET_TODOCOUNT'
export const GET_TODOCOUNT_SUCCESS = 'GET_TODOCOUNT_SUCCESS'